// src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useAccountStore } from './stores/account'
import { useRoute, useRouter } from 'vue-router'

const accountStore = useAccountStore();
const route = useRoute();
const router = useRouter();

async function attemptLogout () {
  try {
      await accountStore.logout();
    } catch (error) {
      console.log()
    } finally {
      accountStore.getAccount();
      // router.push("/");
    }
}

onMounted(() => {
  if(localStorage.getItem('id') !== null) {
    accountStore.getAccount();
  }
})
</script>

<template>
  <router-view />
  <section v-if="accountStore.id" class="absolute top-0 right-0 py-3 px-6 mr-2 mt-2">
      <button
        v-on:click="attemptLogout"
        class="logout-button mx-auto mt-4 py-2 px-4 font-semibold text-md rounded-lg shadow-md bg-white text-gray-900 border border-gray-900 hover:border-transparent hover:text-white hover:bg-gray-900 focus:outline-none"
      >
      <span>
        👋 Hi {{ accountStore.name }}!
      </span>
      </button>
  </section>
  <section v-if="!accountStore.id && route.path !== '/login' && route.path !== '/signup'" class="absolute top-0 right-0 py-3 px-6 mr-2 mt-2">
      <button
        v-on:click="router.push('/login')"
        class="mx-auto mt-4 py-2 px-4 font-semibold text-md rounded-lg shadow-md bg-white text-gray-900 border border-gray-900 hover:border-transparent hover:text-white hover:bg-gray-900 focus:outline-none"
      >
        ✨ Login ✨
      </button>
  </section>
  <section v-if="route.path == '/login' || route.path == '/signup'" class="absolute top-0 right-0 py-3 px-6 mr-2 mt-2">
      <button
        v-on:click="router.push('/')"
        class="mx-auto mt-4 py-2 px-4 font-semibold text-md rounded-lg shadow-md bg-white text-gray-900 border border-gray-900 hover:border-transparent hover:text-white hover:bg-gray-900 focus:outline-none"
      >
        🏠 Home
      </button>
  </section>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

.logout-button:hover span {
  display: none;
}

.logout-button:hover:before {
  content:"😭 Logout?";
}
</style>

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Router, { push, location } from "svelte-spa-router";
  import { wrap } from "svelte-spa-router/wrap";

  import { state } from "./store";
  import { sdk } from "./appwrite";

  import Alert from "./lib/Alert.svelte";
  import Login from "./routes/Login.svelte";
  import SignUp from "./routes/SignUp.svelte";
  import Polls from "./routes/Polls.svelte";
  import Home from "./routes/Home.svelte";

  const logout = async () => {
    try {
      await state.logout();
    } catch (error) {
      state.alert({ color: "red", message: error.message });
    } finally {
      state.init(null);
      push("/");
    }
  };

  const routes = {
    "/": Home,
    "/login": wrap({
      component: Login,
      conditions: [() => !$state.account],
    }),
    "/signup": wrap({
      component: SignUp,
      conditions: [() => !$state.account],
    }),
    "/polls": wrap({
      component: Polls,
      conditions: [() => !!$state.account],
    }),
    "*": Home,
  };

  onMount(async () => {
    try {
      const account = await sdk.account.get();
      state.init(account);
      console.log(account)
    } catch (error) {
      state.init(null);
    }
  });
</script>

<style>
.logout-button:hover span {
  display: none;
}

.logout-button:hover:before {
  content:"😭 Logout?";
}
</style>

<Alert />
<Router {routes} on:conditionsFailed={() => push("/")} />
  
{#if $location !== "/login"}
  {#if $state.account}
  <section class="absolute top-0 right-0 py-3 px-6 mr-2 mt-2">
    <button
      on:click={logout}
      class="logout-button mx-auto mt-4 py-2 px-4 font-semibold text-md rounded-lg shadow-md bg-white text-gray-900 border border-gray-900 hover:border-transparent hover:text-white hover:bg-gray-900 focus:outline-none"
    >
      <span>
        👋 Hi {$state.account.name}!
      </span>
    </button>
  </section>
  {:else}
  <section class="absolute top-0 right-0 py-3 px-6 mr-2 mt-2">
    <button
        on:click={() => push("/login")}
        class="mx-auto mt-4 py-2 px-4 font-semibold text-md rounded-lg shadow-md bg-white text-gray-900 border border-gray-900 hover:border-transparent hover:text-white hover:bg-gray-900 focus:outline-none"
    >
    ✨ Login ✨
    </button>
  </section>
  {/if}
{/if}
